spring.profiles.active: dev
server.port: ${ENV_SERVER_PORT}
spring:
  application:
    name: saving-service
  datasource:
    driver-class-name: ${ENV_DRIVER_CLASS_NAME}
    url: ${ENV_DATASOURCE_URL}
    username: ${ENV_DATASOURCE_SERVICE_USERNAME}
    password: ${ENV_DATASOURCE_SERVICE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

io.kadmos.saving.name: ${ENV_SERVICE_NAME}
---
spring:
  config:
    activate:
      on-profile: dev

ENV_DATASOURCE_URL: jdbc:postgresql://balance-db:5432/kadmos-balance
ENV_DATASOURCE_SERVICE_USERNAME: kadmos-postgres
ENV_DATASOURCE_SERVICE_PASSWORD: kadmos-postgres
ENV_DRIVER_CLASS_NAME: org.postgresql.Driver
ENV_SERVICE_NAME: Default-service
ENV_SERVER_PORT: 8080

